### ISSUE TITLE
bzip2 symlinks appears to be broken

### ISSUE THREAD

**Issue by Arucard1983** [darlinghq/darling-bzip2#1]
During "make install" phase of installation, the following error prevent to finish the process:
CMake Error at src/external/bzip2/cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/home/nosferatu/Transferências/darling/build/x86-64/src/external/bzip2/symlinks/bzcat".
Call Stack (most recent call first):
  src/cmake_install.cmake:70 (include)
  cmake_install.cmake:44 (include)

So the bzcat symlink failure may be bugged.

**Comment by LubosD** [comment]
I hope it's fixed, although I don't understand why the problem only appears here (there are many symlinks installed...).
